### ISSUE TITLE
WebDriverWait is not working for DialogFragment

### ISSUE THREAD

**Issue by pritamkarmakar** [appium/appium-dotnet-driver#72] opened 2015-01-06 21:44 UTC
Problem statement here - http://stackoverflow.com/questions/27807675/webdriverwait-is-not-working-c-appium

**Comment by TikhomirovSergey** [comment] 2015-01-07 19:05
Ok! I have tried to reproduce the problem but I couldn't. 
I have read your logs and I copied them to a gist here: https://gist.github.com/TikhomirovSergey/ea7750d9522e6146614d

I don't like this string: https://gist.github.com/TikhomirovSergey/ea7750d9522e6146614d#file-gistfile1-txt-L420

It looks like there is a problem on the server side. So I advice you to report a bug here: https://github.com/appium/appium/issues. Please attach your code samples to a new ticket. If you don't mind you can attach your built *.apk too. Please describe your environment. As I can see you use 5.0.1 Android plapform. I don't know how current Appium version is friendly to this platform. :(

**Comment by TikhomirovSergey** [comment] 2015-01-07 19:13
As a workaround for now I recommend you to use:

> driver.Manage().TimeOuts().ImplicitlyWait(TimeSpan.FromSeconds(10)); //it can be invoked once

**Comment by TikhomirovSergey** [comment] 2015-01-10 22:43
Ok. This is not .Net client issue. The root cause descriptions are below:
https://github.com/appium/appium/pull/4252
https://github.com/appium/appium/issues/4368

Please anybody close this ticket.

**Closed** 2015-01-11 01:17 UTC
