### ISSUE TITLE
unknown server-side error occurred

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium-dotnet-driver#275] opened 2018-10-23 11:06 UTC
## Description
My test suddenly fails in between without any information.
Exception I get is :

`OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
`

## Environment

* .NET client build version or git revision if you use some shapshot: 4.0.0.4 -beta
* Appium server version or git revision if you use some shapshot: 1.9.1
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Samsung Galaxy S8 - Android O
* Real device or emulator/simulator: Real device

## Details

`{"platformName":"Android","automationName":"UIAutomator2","platformVersion":"8.0","deviceName":"Galaxy S8","printPageSourceOnFindFailure":true,"appPackage":"com.xxx.xxx","appActivity":".MainActivity","autoWebview":true,"nativeWebScreenshot":true,"newCommandTimeout":500,"chromedriverUseSystemExecutable":false}`

## Code To Reproduce Issue [ Good To Have ]
randomly fails at any line of code.

## Appium Logs

[gist](https://gist.github.com/MummanaSubramanya/9ebc61a8cd6e2e5adcf60a70a6df48d2) 

Please check from line 63. In the previous runs entering password never got exception.

**Comment by MummanaSubramanya** [comment] 2018-10-24 09:00
@akinsolb : any idea how to resolve this issue

**Comment by KazuCocoa** [comment] 2018-10-24 14:18
What about skipping `hide_keyboard` once?
Below error shows the view has no keyboard.

```
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.hideKeyboard() with args: [null,null,null,null,"e4db4bd8-1212-4eee-8890-d1f40abff721"]
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell dumpsys input_method'
[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:.
[debug] [UiAutomator2] [UIAutomator2] Time: 14.077
[debug] [UiAutomator2] [UIAutomator2] OK (1 test)
[debug] [W3C] Encountered internal error running command: Error: Soft keyboard not present, cannot hide keyboard
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (C:\node_modules\appium\node_modules\appium-android-driver\lib\commands\general.js:72:11)
[debug] [W3C]     at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/e4db4bd8-1212-4eee-8890-d1f40abff721/appium/device/hide_keyboard 500 1716 ms - 1143
[HTTP]
```

**Comment by MummanaSubramanya** [comment] 2018-10-24 16:44
if the key board is there it will close else exception will be catch and will move to next step. As mentioned above the test randomly fails at any step. This was working fine 1.8.1 i dint face any issue with android version 6. I am facing this issue in 1.9.1 Android O UIAutomator2.

**Comment by KazuCocoa** [comment] 2018-10-24 17:08
So, it looks the cause is sometimes keyboard doesn't appear after below `value` command in this case.

```
[HTTP] --> POST /wd/hub/session/e4db4bd8-1212-4eee-8890-d1f40abff721/element/0.062111065885706696-1/value
[HTTP] {"text":"test_xxx@xxxtl.be","value":["t","e","s","t","_","f","l","i","x","@","f","p","t","l",".","b","e"]}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/e4db4bd8-1212-4eee-8890-d1f40abff721/element/0.062111065885706696-1/value' to command name 'setValue'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/e4db4bd8-1212-4eee-8890-d1f40abff721/element/0.062111065885706696-1/value] to [POST http://127.0.0.1:8000/wd/hub/session/735d1ab927f3b149bd6648c535199641/element/0.062111065885706696-1/value] with body: {"text":"test_xxx@xxxtl.be","value":["t","e","s","t","_","f","l","i","x","@","f","p","t","l",".","b","e"]}
[BaseDriver] Shutting down because we waited 500 seconds for a command
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Matched '/' to command name 'deleteSession'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8208/wd/hub/session/48c47090-20e8-4c36-bf9f-15d9549c9aba] with no body
[Appium] Closing session, cause was 'New Command Timeout of 500 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 4fca0eb3-0b5e-423e-85ec-746f8f8144b3 from our master session list
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"48c47090-20e8-4c36-bf9f-15d9549c9aba\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell am force-stop com.xxx.xxx'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8208
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 forward --remove tcp\:8208'
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"735d1ab927f3b149bd6648c535199641","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 735d1ab927f3b149bd6648c535199641 with e4db4bd8-1212-4eee-8890-d1f40abff721
[HTTP] <-- POST /wd/hub/session/e4db4bd8-1212-4eee-8890-d1f40abff721/element/0.062111065885706696-1/value 200 1022 ms - 76
[HTTP]
```

- Did you use UIAutomator2 for Android 6 before?
- The value command failed because of timeout, `Shutting down because we waited 500 seconds for a command`. When the timeout error happened, could you observe some text typed?
- If _randomly fails at any line of code._ is because of this timeout error, you can `Shutting down because we waited 500 seconds for a command` then. Could you see the timeout error logs when your issue happened?

**Comment by MummanaSubramanya** [comment] 2018-10-25 08:53
@KazuCocoa 

1) Nope I was using Appium for android 6 and for android 6+ i was told to use UIAutomator2
2) It dint never waited 500 seconds it crashed immediately after entering the password. 

as mentioned hide keyboard is not the issue. this is just one of the instance where it failed randomly at a particular step. I ran the same test second time the the test again failed with same error at different step. If you think the hide keyboard was an issue it could have failed at the same step as previous run.

**Comment by YuryKebets** [comment] 2018-10-29 14:38
I had a similar problem. After resetting the data on the phone, the error disappeared.

**Comment by MummanaSubramanya** [comment] 2018-10-29 15:25
@KazuCocoa : 

below are logs of same test which failed becuas e of same reason.

`[HTTP] {}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/bfac4c3d-d4c5-4ec2-a4f2-41242ac88245/element/0.2629045569547377-6/click' to command name 'click'
[JSONWP Proxy] Proxying [POST /wd/hub/session/bfac4c3d-d4c5-4ec2-a4f2-41242ac88245/element/0.2629045569547377-6/click] to [POST http://127.0.0.1:8000/wd/hub/session/f33e39692d86da86255aaac27af3411a/element/0.2629045569547377-6/click] with body: {}
[JSONWP Proxy] Got response with status 200: {"sessionId":"f33e39692d86da86255aaac27af3411a","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId f33e39692d86da86255aaac27af3411a with bfac4c3d-d4c5-4ec2-a4f2-41242ac88245
[HTTP] <-- POST /wd/hub/session/bfac4c3d-d4c5-4ec2-a4f2-41242ac88245/element/0.2629045569547377-6/click 200 388 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/bfac4c3d-d4c5-4ec2-a4f2-41242ac88245/element
[HTTP] {"using":"xpath","value":"//div[@ng-repeat='rows in userGroups | gridList:3']//p[text()='All']"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/bfac4c3d-d4c5-4ec2-a4f2-41242ac88245/element' to command name 'findElement'
[JSONWP Proxy] Proxying [POST /wd/hub/session/bfac4c3d-d4c5-4ec2-a4f2-41242ac88245/element] to [POST http://127.0.0.1:8000/wd/hub/session/f33e39692d86da86255aaac27af3411a/element] with body: {"using":"xpath","value":"//div[@ng-repeat='rows in userGroups | gridList:3']//p[text()='All']"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"f33e39692d86da86255aaac27af3411a","status":0,"value":{"ELEMENT":"0.2629045569547377-7"}}
[JSONWP Proxy] Replacing sessionId f33e39692d86da86255aaac27af3411a with bfac4c3d-d4c5-4ec2-a4f2-41242ac88245
[HTTP] <-- POST /wd/hub/session/bfac4c3d-d4c5-4ec2-a4f2-41242ac88245/element 200 309 ms - 106
[HTTP] 
[BaseDriver] Shutting down because we waited 500 seconds for a command
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[JSONWP Proxy] Matched '/' to command name 'deleteSession'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8201/wd/hub/session/df5006bd-03ee-400e-a726-c8f87a75c083] with no body
[Appium] Closing session, cause was 'New Command Timeout of 500 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 498a758a-638d-4f7b-8734-9905d56e111f from our master session list
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"df5006bd-03ee-400e-a726-c8f87a75c083\",\"status\":0,\"value\":\"Session deleted\"}"
[ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell am force-stop com.essent.flix'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8201 
[ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 forward --remove tcp\:8201'
[UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:.
[UiAutomator2] [UIAutomator2] Time: 19.07
[UiAutomator2] [UIAutomator2] OK (1 test)`

**Comment by MummanaSubramanya** [comment] 2018-10-29 15:56
@KazuCocoa @mykola-mokhnach 

https://gist.github.com/MummanaSubramanya/0ae2fee349d23bda9b9646b243a1291e

This issue seems to be an interesting issue. At line 14 the appium server shutdown becuase of unknown error. but then again at 34 it tries for searching for  element and hence my code throws exception:
`OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
`

**Comment by MummanaSubramanya** [comment] 2018-10-29 15:59
@YuryKebets : mine is new device. I dnt believe its because of data issue.

**Comment by akinsolb** [comment] 2018-10-29 16:04
@MummanaSubramanya Can you post a gist of your stack trace along with each server log gist? 
Also, do you run the server under a proxy?

**Comment by MummanaSubramanya** [comment] 2018-10-29 16:13
@akinsolb : 
this is first server log which failed  when entering the username: https://gist.github.com/MummanaSubramanya/9ebc61a8cd6e2e5adcf60a70a6df48d2

this the second server log of the same test failed at different step when entering the password but same exception:
https://gist.github.com/MummanaSubramanya/0ae2fee349d23bda9b9646b243a1291e

this the only exception I got `OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET` for both the tests.

If you check the 2nd gist at line 14 the appium server shutdown because of unknown reason  but then again at 34 it tries for searching for element and hence my code throws above exception

**Comment by MummanaSubramanya** [comment] 2018-10-29 17:14
@akinsolb : No 1.8.1 used to work fine.

**Comment by MummanaSubramanya** [comment] 2018-10-30 09:28
Im facing this issue with both CLI and Desktop version version 1.9.1 :(

**Comment by akinsolb** [comment] 2018-10-30 09:45
Do you have this issue in the previous versions of appium server i.e. 1.8?

**Comment by KazuCocoa** [comment] 2018-10-31 07:04
Could you get logcat log when you have a chance? @MummanaSubramanya 
The server error is a general message. If something happens in server side running in Android, we probably can get logs via logcat.

**Comment by MummanaSubramanya** [comment] 2018-11-02 17:11
this issue https://github.com/appium/appium/issues/11606 says the same. you still think its an app issue. I dnt believe it @KazuCocoa  @mykola-mokhnach

**Comment by MummanaSubramanya** [comment] 2018-11-02 17:14
@akinsolb : In 1.8.1 i never had issue i was using automationName: Appium but since I had to support for Android O I started using 1.9.1 with AutomationName:UIAutomator2. I can see this issue windows and Linux machine also.

**Comment by KazuCocoa** [comment] 2018-11-03 01:52
As I commented in https://github.com/appium/appium-dotnet-driver/issues/275#issuecomment-434582530 , we can dig into further if we can get logcat.
Do you have a change to get them?

**Comment by MummanaSubramanya** [comment] 2018-11-05 10:53
@KazuCocoa : it very tough for me because the tests are not failing when I try to run in individually. They fail in bulk.
As I told you 1.8.1 used to work fine without any issue.  Here is the latest server log
`--> POST /wd/hub/session/dd7aba1e-8400-44b7-9794-da09f4bcee4d/element
[HTTP] {"using":"xpath","value":"//button[normalize-space(.)='CONFIRM']"}
[W3C (dd7aba1e)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/dd7aba1e-8400-44b7-9794-da09f4bcee4d/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/dd7aba1e-8400-44b7-9794-da09f4bcee4d/element] to [POST http://127.0.0.1:8000/wd/hub/session/e427a3e971b4040af7f307fc461d37ac/element] with body: {"using":"xpath","value":"//button[normalize-space(.)='CONFIRM']"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"e427a3e971b4040af7f307fc461d37ac","status":100,"value":{"message":"chrome not reachable\n  (Session info: chrome=70.0.3538.80)\n  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.62-v7+ armv7l)"}}
[JSONWP Proxy] Got an unexpected response: {"sessionId":"e427a3e971b4040af7f307fc461d37ac","status":100,"value":{"message":"chrome not reachable\n  (Session info: chrome=70.0.3538.80)\n  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.62-v7+ armv7l)"}}
[debug] [W3C (dd7aba1e)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/dd7aba1e-8400-44b7-9794-da09f4bcee4d/element has failed
[debug] [W3C (dd7aba1e)]     at /home/pi/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:180:13
[debug] [W3C (dd7aba1e)]     at Generator.next (<anonymous>)
[debug] [W3C (dd7aba1e)]     at asyncGeneratorStep (/home/pi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (dd7aba1e)]     at _next (/home/pi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [W3C (dd7aba1e)]     at <anonymous>
[debug] [MJSONWP] Matched JSONWP error code 100 to UnknownError
[HTTP] <-- POST /wd/hub/session/dd7aba1e-8400-44b7-9794-da09f4bcee4d/element 500 67 ms - 1059
[HTTP]
[HTTP] --> GET /wd/hub/session/dd7aba1e-8400-44b7-9794-da09f4bcee4d/screenshot`

**Comment by MummanaSubramanya** [comment] 2018-11-05 10:56
In the above comment its able to find the element but in message body it says chrome is unreachable.

**Comment by MummanaSubramanya** [comment] 2018-11-05 11:01
Here is the another failed server Log 

`[HTTP] {"using":"xpath","value":"//button[normalize-space(.)='Login']"}
[W3C (32d21c9e)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/32d21c9e-eb9f-410e-b996-12293c216e60/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/32d21c9e-eb9f-410e-b996-12293c216e60/element] to [POST http://127.0.0.1:8000/wd/hub/session/2c79e97bfc7528be3fc6a04821393021/element] with body: {"using":"xpath","value":"//button[normalize-space(.)='Login']"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"2c79e97bfc7528be3fc6a04821393021","status":100,"value":{"message":"chrome not reachable\n  (Session info: chrome=70.0.3538.80)\n  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.62-v7+ armv7l)"}}
[JSONWP Proxy] Got an unexpected response: {"sessionId":"2c79e97bfc7528be3fc6a04821393021","status":100,"value":{"message":"chrome not reachable\n  (Session info: chrome=70.0.3538.80)\n  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.62-v7+ armv7l)"}}
[debug] [W3C (32d21c9e)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/32d21c9e-eb9f-410e-b996-12293c216e60/element has failed
[debug] [W3C (32d21c9e)]     at /home/pi/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:180:13
[debug] [W3C (32d21c9e)]     at Generator.next (<anonymous>)
[debug] [W3C (32d21c9e)]     at asyncGeneratorStep (/home/pi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (32d21c9e)]     at _next (/home/pi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [W3C (32d21c9e)]     at <anonymous>
[debug] [MJSONWP] Matched JSONWP error code 100 to UnknownError
[HTTP] <-- POST /wd/hub/session/32d21c9e-eb9f-410e-b996-12293c216e60/element 500 52 ms - 1059
[HTTP]
[HTTP] --> GET /wd/hub/session/32d21c9e-eb9f-410e-b996-12293c216e60/screenshot
[HTTP] {}
[debug] [W3C (32d21c9e)] Calling AppiumDriver.getScreenshot() with args: ["32d21c9e-eb9f-410e-b996-12293c216e60"]
[debug] [JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8210/wd/hub/session/e3c28429-f774-45c7-a640-a396b0a4ee0f/screenshot] with no body
[JSONWP Proxy] Got an unexpected response: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
[debug] [W3C (32d21c9e)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
[debug] [W3C (32d21c9e)]     at /home/pi/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:13
[debug] [W3C (32d21c9e)]     at Generator.throw (<anonymous>)
[debug] [W3C (32d21c9e)]     at asyncGeneratorStep (/home/pi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (32d21c9e)]     at _throw (/home/pi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
[debug] [W3C (32d21c9e)]     at <anonymous>
[HTTP] <-- GET /wd/hub/session/32d21c9e-eb9f-410e-b996-12293c216e60/screenshot 500 23 ms - 732
[HTTP]
[HTTP] --> POST /wd/hub/session/32d21c9e-eb9f-410e-b996-12293c216e60/appium/app/close
[HTTP] {}
[debug] [W3C (32d21c9e)] Calling AppiumDriver.closeApp() with args: ["32d21c9e-eb9f-410e-b996-12293c216e60"]
[debug] [ADB] Running '/home/pi/android-sdk-linux/platform-tools/adb -P 5037 -s 5200defef0714537 shell am force-stop com.fifthplay.fifthplay'
[debug] [AndroidDriver] Stopping chromedriver for context WEBVIEW_com.fifthplay.fifthplay
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/2c79e97bfc7528be3fc6a04821393021] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"2c79e97bfc7528be3fc6a04821393021\",\"status\":0,\"value\":null}"
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [W3C (32d21c9e)] Responding to client with driver.closeApp() result: null
[HTTP] <-- POST /wd/hub/session/32d21c9e-eb9f-410e-b996-12293c216e60/appium/app/close 200 177 ms - 14`

**Comment by MummanaSubramanya** [comment] 2018-11-05 12:40
[adhlogcat-Error.txt](https://github.com/appium/appium-dotnet-driver/files/2548369/adhlogcat-Error.txt)
 attaching the logcat @KazuCocoa

**Comment by MummanaSubramanya** [comment] 2018-11-05 13:05
https://gist.github.com/MummanaSubramanya/93cee47cc30d67780acc94343e8edf57 

here is the chromedriver log for reference

**Comment by mykola-mokhnach** [comment] 2018-11-05 13:07
Yep, I don't think this is something that can be fixed with appium. Please report this bug to chromedriver tracker

**Comment by mykola-mokhnach** [comment] 2018-11-05 13:09
Duplicate of https://github.com/appium/appium/issues/11628

**Closed by mykola-mokhnach** 2018-11-05 13:09 UTC
