### ISSUE TITLE
W3C Protocol expects any of script, pageload, or implicit to be set appium 1.8.1

### ISSUE THREAD

**Issue by rwilliamshgem** [appium/appium-dotnet-driver#233] opened 2018-06-15 11:35 UTC
The problem
Just updated appium through npm to the latest version (1.8.1) from 1.7.1 and my automation is failing trying to set the implicit timeout wait.

Environment
Appium version (or git revision) that exhibits the issue: 3.0.0.2
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: 1.8.1
Node.js version (unless using Appium.app|exe): 8.11.0
Mobile platform/version under test: Android 6/ios 11.4
Real device or emulator/simulator: real-device
Appium CLI or Appium.app|exe: appium cli
Details
The exception given out is below:

OpenQA.Selenium.WebDriverException
HResult=0x80131500
Message=Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":30000}
Source=WebDriver
StackTrace:
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteTimeouts.ExecuteSetTimeout(String timeoutType, TimeSpan timeToWait)
at OpenQA.Selenium.Remote.RemoteTimeouts.set_ImplicitWait(TimeSpan value)
at GemApp.ManagerApp.Tests.UI.SpecflowIoC.BeforeScenario() in C:\Projects\GemApp.ManagerApp-NetStandard\GemApp.ManagerApp.Tests.UI\SpecflowIoC.cs:line 46

Link to Appium logs
[W3CProtocol.txt](https://github.com/appium/appium-dotnet-driver/files/2105890/W3CProtocol.txt)

Code To Reproduce Issue [ Good To Have ]
Create a AndroidDriver
followed by line below
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);

**Comment by kseeman** [comment] 2018-06-28 13:41
I am also seeing this same behavior after upgrading to appium 1.8.1. Has there been any resolution with this?

**Comment by skyscarer** [comment] 2018-07-11 13:40
I'm also seeing this behaviour. 

System.InvalidOperationException: 'Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":30000}'

All I did to get this error was to set the following code:
Driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);

**Comment by rwilliamshgem** [comment] 2018-07-16 09:31
@kseeman no resolution that i'm aware of, I'm going to look into using explicit waits instead so that i can use the latest appium verison

**Comment by jackwangchs** [comment] 2018-07-26 06:38
Any updates on this issue? I got the same error on MacOS

- Appium 1.8.2 beta
- Appium WebDriver 3.0.0.2
- Selenium Support 3.12.1
- Selenium WebDriver 3.12.1

But it works well on my Windows platform, with the same/similar tools version

- Appium 1.8.1
- Appium donet driver 3.0.0.2
- WebDriver 3.12.1
- WebDriver Support 3.12.1

What makes the difference?

Due to the different, I'm using different wait methods between MacOS and Windows, now I'm going to merge them. And want to use implicitly wait to make it simple. Can anyone help on fixing this issue?

**Comment by akinsolb** [comment] 2018-07-26 07:31
@jackwangchs can you try building and running appium server from source? As I can no longer reproduce the error doing so.

**Comment by jackwangchs** [comment] 2018-07-26 07:39
@akinsolb I see java-client has fixed the problem https://github.com/appium/appium-dotnet-driver/issues/229, are you sure the dotnet issue from Appium server, instead dotnet client?

**Comment by akinsolb** [comment] 2018-07-26 07:48
Very sure. My local repo currently has appium (master branch) with selenium v3.13 and I ran tests against appium from source. I just haven’t had the time to find the changeset that resolved the issue. Will look into it further today but give it a try.

**Comment by jackwangchs** [comment] 2018-07-26 08:10
@akinsolb that's okay. I will try with appium server from source. Thanks!

**Comment by jackwangchs** [comment] 2018-07-26 08:46
@akinsolb After building from source, it shows 1.8.0-beta. Is it package.json issue? How to confirm whether installed from the latest source?

**Comment by akinsolb** [comment] 2018-07-26 21:15
@jackwangchs I presume after cloning, building and launching appium server from source, running the command 'appium -v' returns "1.8.0-beta"? I believe this is source. 

@mykola-mokhnach Can you confirm whether this issue is resolved by https://github.com/appium/appium-base-driver/pull/231? and if so, close the issue?

**Comment by jackwangchs** [comment] 2018-07-27 02:32
@akinsolb yes, the version shows "1.8.0-beta". I found the `"version": "1.8.0-beta"` in the _package.json_ file

**Comment by rwilliamshgem** [comment] 2018-07-27 11:16
If this is fixed by the beta version when will it be released as I'm having issues getting my iOS automation to use explicit waits and it would make it simpler if i could use implicit waits as my code was before

**Comment by theAshenfire** [comment] 2018-08-26 12:40
I have just encountered the exact same issue on my machine, using server from nuget.
Steps to reproduce:
1. install appium 1.8.1 (npm install -g appium)
2. download latest version of appium-dotnet-driver
3. set up and start an android emulator on my machine with version 4.4.2
4. start up appium (command: appium -a localhost)
5.run any test under Appium.Intergration.Test.Android

expected result: test completes successfully
actual result: i get the following error:
OpenQA.Selenium.WebDriverException : Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":5000}

i found that when i comment out the following line in test then it passes
driver.Manage().Timeouts().ImplicitWait = Env.IMPLICIT_TIMEOUT_SEC;

please help me resolve this issue

**Comment by tomerpeled** [comment] 2018-09-18 21:35
Any updates?

**Comment by akinsolb** [comment] 2018-09-18 21:56
@tomerpeled which appium server version are you using?

**Comment by tomerpeled** [comment] 2018-09-18 21:58
1.8.1

**Comment by akinsolb** [comment] 2018-09-18 22:10
Right, I can only advise that you update to the latest version of appium server, hoping it will handle this issue.
Furthermore, If you are using the .Net bindings with Selenium > v3.8, then this won't be resolved until the next beta release which will support Selenium 3.14.

**Closed by akinsolb** 2018-09-18 22:10 UTC
