### ISSUE TITLE
Explicit Wait not working in Appium 1.8.0 with c# client

### ISSUE THREAD

**Issue by Gocoollnath** [appium/appium-dotnet-driver#225] opened 2018-05-10 12:42 UTC
## Description

Explicit wait not working and the sever doesn't wait for the time specified for the object to be present

## Environment

Appium version 1.8.0
Desktop OS/version used to run Appium: Windows 10 Pro
Node.js version (unless using Appium.app|exe): 8.10.0
Mobile platform/version under test: Android API 25 ,v7.1.1
Real device or emulator/simulator: Real Device Samsung Tab
Appium CLI or Appium.app|exe: both
IDE: VisualStudio 2017 Enterprise and C# as coding language

## Code To Reproduce Issue [ Good To Have ]

new WebDriverWait(driver, TimeSpan.FromMilliseconds(50000)).Until(ExpectedConditions.ElementToBeClickable(By.ClassName("android.widget.Spinner")));

**and also tried this code**

new WebDriverWait(driver,FromMilliseconds(50000)).Until(X=>X.FindElement(By.Id("elementid");

WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(50));
             Func<IWebDriver, IWebElement> waitForElement = new Func<IWebDriver, IWebElement>((IWebDriver Web) =>
             {

                 IWebElement element = Web.FindElement(By.XPath("//android.widget.Button[@text='OK']"));
                 if (element.GetAttribute("style").Contains("red"))
                 {
                     return element;
                 }
                 return null;
             });
IWebElement ok =wait.Until(waitForElement);

## Ecxeption stacktraces

Test Name:	TestMethod1
Test FullName:	UnitTestProject1.UnitTest1.TestMethod1
Test Source:	C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\UnitTest1.cs : line 25
Test Outcome:	Failed
Test Duration:	0:01:49.3963396

Result StackTrace:	

at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElement(By by)
   at AMCS_Mobile.Page_Objects.Vehicle_Selector_Objects.OK_btn() in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\Page_Objects\Vehicle_Selector_Objects.cs:line 36
   at AMCS_Mobile.Vehicle_Selector.Vehicle_selector.Vehicle_Selector(String Vehiclename) in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\App_Modules\Vehicle_selector.cs:line 30
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\UnitTest1.cs:line 29
Result Message:	
Test method UnitTestProject1.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: An element could not be located on the page using the given search parameters.

## Link to Appium logs

https://gist.github.com/Gocoollnath/547096033a7ff6a9bc4c89b9f30f7d1b

**Comment by wjvii** [comment] 2018-08-18 14:30
I am running into the same issue. When I use WebDriverWait it does not appear to actually wait for the time specified.

**Comment by jankratochvilcz** [comment] 2018-08-20 19:01
I also seem to be running into this issue :-/

**Comment by vsushyk** [comment] 2018-08-21 22:33
I'm having the same issue.
Appium CLI: 1.8.1
Appium app: 1.6.3

**Comment by tomerpeled** [comment] 2018-09-19 12:17
Any workaround?

**Comment by ArekGr** [comment] 2018-10-29 14:08
Same issue using Appium.WebDriver 3.0.0.2.
WebDriverWait does not wait for the time specified.

**Comment by spogulis** [comment] 2019-05-10 11:40
Having the same issue with Selenium.WebDriver 3.141.0. Any plan to fix this?

**Comment by lanzelot1989** [comment] 2019-06-19 05:34
Using 
`new WebDriverWait(Driver, timeout).Until(func);`
is working fine for us. Are you aware that the passed function needs to return a boolean?

Maybe you can try one of these

`new WebDriverWait(driver, FromMilliseconds(50000)).Until(drv => drv.FindElement(By.Id("elementid")).Displayed);
new WebDriverWait(driver, FromMilliseconds(50000)).Until(drv => drv.FindElements(By.Id("elementid")).Any());
`

I have to say that I also did not have much success when using ExpectedConditions (so I can give no guidance here).

**Comment by alexp1980** [comment] 2019-11-19 12:06
This is not working for me either. Tried various WinAppDriver versions. Works fine with the webdrivers.

**Comment by nramprakash88** [comment] 2021-02-24 04:55
Facing the same issue using Appium.WebDriver 4.2.1.
I am using DefaultWait and it does not wait for the time specified. I set a wait time of 5 seconds. But it is taking more than that(sometimes even 20+ seconds)
Any update on this ?

**Comment by EbenZhang** [comment] 2021-04-20 04:19
I did a bit research of this issue, but not totally sure about the second point
- Quite obvious that the ImplicitWait time has to be smaller than the one you passed to WebDriverWait. So you need to set it to a small amount and revert your change after the WebDriverWait.
- The WebDriverWait is expecting a NotFoundException when element not found. But seems appnium is throwing WebDriverException instead.

**Comment by giorgitedi** [comment] 2022-10-07 13:58
@EbenZhang Adding IgnoreExceptionTypes worked for me but when this is going to be fixed?

**Comment by Dor-bl** [comment] 2022-11-04 17:59
@Gocoollnath Can you please try with appium 2.0? Appium 1.0 is out of support

**Comment by Dor-bl** [comment] 2022-11-13 19:15
Closing this issue since it's the expected behavior. 
As @EbenZhang mentioned, you should use:
`wait.IgnoreExceptionTypes(typeof(NotFoundException) `.

**Closed by Dor-bl** 2022-11-13 19:15 UTC
Labels: NeedsInvestigation
