### ISSUE TITLE
appium 4.0.0.5-beta BackgroundApp(TIME) doesn't wait in background expected TIME return live immediately

### ISSUE THREAD

**Issue by vatsikmax** [appium/appium-dotnet-driver#309] opened 2019-01-30 17:00 UTC
## Description

appium 4.0.0.5-beta BackgroundApp(TIME) function doesn't wait in background expected TIME return live immediately

## Environment

* Appium nuget package version 4.0.0.5-beta:
* Appium server version 1.9.1:
* Node.js version 8.11.2:
* Android/8.1.0:
* Real device:

## Code To Reproduce Issue [ Good To Have ]

appiumDriver.BackgroundApp(10)

## Exception stacktraces

NO exception

## Link to Appium logs

https://gist.github.com/vatsikmax/e83998c614f86ccebc0be8ee09a8d9f4

**Comment by KazuCocoa** [comment] 2019-02-01 15:20
In android case, the payload should be `{"seconds": 10}`. Not `{"seconds":{"timeout":10}}`
Maybe, this is the cause...
(The latter case is for xcuitest)

**Comment by matthew-horrocks** [comment] 2019-06-24 15:01
Just been looking at this.

What's the best way to distinguish between Android` xcuitest` and `uiautomator2` in this method?

https://github.com/appium/appium-dotnet-driver/blob/4ec4c8b5447b7b5052f2b9c3a1a848ad62def410/src/Appium.Net/Appium/AppiumDriver.cs#L268

Presumably `uiautomator2` should be;

`Execute(AppiumDriverCommand.BackgroundApp,
                AppiumCommandExecutionHelper.PrepareArgument("seconds"));`

and xcuitest should remain as;

`Execute(AppiumDriverCommand.BackgroundApp,
                AppiumCommandExecutionHelper.PrepareArgument("seconds", AppiumCommandExecutionHelper.PrepareArgument("timeout", seconds)));`

**Comment by matthew-horrocks** [comment] 2019-08-28 16:15
Would be great to get this fixed. I'm happy to do a PR for the fix above.

**Comment by akinsolb** [comment] 2019-08-28 16:50
@matthew-horrocks go for it. I want to do a release this week, so if it doesn’t make the major release it’ll be in the minor

**Comment by matthew-horrocks** [comment] 2019-09-06 11:01
I had a look at this. Turns out it's not as simple as I first thought.

**Android**
Updated `public void BackgroundApp(int seconds)` to  `Execute(AppiumDriverCommand.BackgroundApp, AppiumCommandExecutionHelper.PrepareArgument("seconds"));` called it using `appiumDriver.BackgroundApp(30);`. This works fine for Android - the app goes into the background and returns 30 seconds later.

**iOS**
Updated `public void BackgroundApp(int seconds)` to `Execute(AppiumDriverCommand.BackgroundApp, AppiumCommandExecutionHelper.PrepareArgument("seconds"));` and called it using `appiumDriver.BackgroundApp(30);`. For iOS this does not work (as expected via https://github.com/appium/appium-dotnet-driver/issues/309#issuecomment-459757398).

I tested with `Execute(AppiumDriverCommand.BackgroundApp, AppiumCommandExecutionHelper.PrepareArgument("seconds", AppiumCommandExecutionHelper.PrepareArgument("timeout", seconds)));` and called it with `appiumDriver.BackgroundApp(30);`. I found the app gets sent to the background but returns immediately.

The BrowserStack App Automate appium logs for this operation looks like;

```
2019-09-06 10:22:22:293 - [HTTP] {"seconds":{"timeout":30}}
2019-09-06 10:22:22:294 - [debug] [MJSONWP (7c0addb4)] Calling AppiumDriver.background() with args: [{"timeout":30},"7c0addb4-55a8-4dba-a3cb-fabc2d424687"]
2019-09-06 10:22:22:294 - [debug] [XCUITest] Executing command 'background'
2019-09-06 10:22:22:304 - [XCUITest] Proxying to WDA with an unknown route: POST /wda/deactivateApp
2019-09-06 10:22:22:306 - [debug] [JSONWP Proxy] Proxying [POST /wda/deactivateApp] to [POST http://localhost:8402/session/EF38E1DA-F53A-4DD3-82AA-9834CE3700B6/wda/deactivateApp] with body: {"duration":0.03}
2019-09-06 10:22:26:855 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"EF38E1DA-F53A-4DD3-82AA-9834CE3700B6","status":0}
2019-09-06 10:22:26:856 - [debug] [XCUITest] Connection to WDA timed out
2019-09-06 10:22:26:856 - [debug] [iProxy] recv failed: Operation not permitted
2019-09-06 10:22:26:856 - [debug] [MJSONWP (7c0addb4)] Responding to client with driver.background() result: {}
```

The `{"duration":0.03}` looks a bit suspicious. So I tried `appiumDriver.BackgroundApp(300);` and the logging returned;

```
2019-09-06 10:41:10:497 - [debug] [WD Proxy] Proxying [POST /wda/deactivateApp] to [POST http://localhost:8403/session/9101A2E1-9990-4A52-A9E9-F13068BD508E/wda/deactivateApp] with body: {"duration":0.3}
```

The `{"duration":0.3}` still looks a bit suspicious. So I tried `appiumDriver.BackgroundApp(30000);` and the logging returned a reasonable `duration` and the app went into the background and returned as expected;

```
2019-09-06 10:43:52:328 - [debug] [WD Proxy] Proxying [POST /wda/deactivateApp] to [POST http://localhost:8405/session/97A96FC3-E66E-4507-8AFA-80207215A94B/wda/deactivateApp] with body: {"duration":30}
```

Two things;

I'm not sure if this iOS `seconds` conversion bug is in another part of the appium/selenium/browserstack chain or something that should be fixed in this repo.

I'm not sure how to handle different iOS and Android ` Execute()` calls in `BackgroundApp()` in `AppiumDriver.cs`.

**Comment by mykola-mokhnach** [comment] 2019-09-06 11:35
@matthew-horrocks 

https://github.com/appium/appium/issues/7741
https://github.com/appium/java-client/blob/ef719245954855a3ed098e0584fad15453ec6693/src/main/java/io/appium/java_client/ios/IOSDriver.java#L178
https://github.com/appium/java-client/blob/1991a8a0f9e4a3ff467dbb713cb5c51c8edc060f/src/main/java/io/appium/java_client/InteractsWithApps.java#L104

should give you more understanding on what is going on. In general we wanted to switch the old format with `seconds` argument to the new one, which accepts an object, where the timeout is set in milliseconds. WDA itself accepts the parameter as float seconds.

**Closed** 2019-12-13 17:15 UTC
Labels: Bug
