### ISSUE TITLE
Drug n drop action 

### ISSUE THREAD

**Issue by pashidlos** [appium/appium-dotnet-driver#90] opened 2015-06-11 12:52 UTC
Hi there! 

I'm using code from examples;

``` c#
ITouchAction touchAction = new TouchAction(driver) 
                .Press (startX, startY)
                .Wait (duration)
                .MoveTo (endX, endY)
                .Release ();
touchAction.Perform();
```

And i'm getting 'System.NotImplementedException' here (this.Execute):

``` c#
public void PerformTouchAction(TouchAction touchAction)
        {
            if (null == touchAction)
            {
                return; // do nothing
            }

            var parameters = new Dictionary<string, object>();
            parameters.Add("actions", touchAction.GetParameters());
            this.Execute(AppiumDriverCommand.TouchActionV2Perform, parameters);
        }
```

What i'm doing wrong?

**Comment by mellamojaja** [comment] 2015-06-18 09:45
I had the same problem. As far as I know, all end up in the "Execute" method of the class "RemoteWebDriver", witch is virtual and should be implemented in the "AppiumDriver" class. the problem is this implementation is missing and you get the "Not implemented" exception when trying to use it. 

This would affect the touch and multitouch actions and every method that uses "Execute", like Orientation, GetAppString, LockDevice, Rotation, StartActivity, etc.

Does anyone knows if this is the desirable behaviour? Is this a pending work or just a bug of any (weird) kind?

**Comment by Jonahss** [comment] 2015-06-18 17:29
I didn't know those methods weren't working. So if this is an issue, it
would be a bug, not by design.

**Comment by Astro03** [comment] 2015-06-19 18:50
The not implemented exception would be since @TikhomirovSergey  was talking bout moving functionality out of here into the selenium driver. @TikhomirovSergey  might have more insight on this.

**Comment by pashidlos** [comment] 2015-08-19 09:02
I found this answer: http://stackoverflow.com/questions/15791962/webdriver-with-touch-events
And get my task resolved with jQuery.

Will it be done in appium?

**Comment by Dor-bl** [comment] 2022-11-13 06:01
Closing the issue since Touch actions will be deprecated in the upcoming release. Please use W3C actions

**Closed by Dor-bl** 2022-11-13 06:01 UTC
