### ISSUE TITLE
[Bug]: Setting window Position causes UnsupportedOperationError

### ISSUE THREAD

**Issue by sudo-plz** [appium/appium-dotnet-driver#812] opened 2024-08-02 13:44 UTC
## Description

When setting either the Size or Position of the window, it returns the following error:
`BadParametersError: Parameters were incorrect. We wanted {"required":["x","y","width","height"]} and you sent ["x","y"]`

## Environment

* Appium: v2.11.2
* OS: Windows
* Node.js version: v20.16.0
* Driver: appium-windows-driver 2.12.29

## Details

Please provide more details, if necessary.
Others experience similar problems without solutions posted e.g. [here](https://github.com/appium/appium/issues/15923#issuecomment-1499118053).

## Code To Reproduce Issue [ Good To Have ]

In any of the Integration tests: `Manage().Window.Position = new System.Drawing.Point(0, 0);`

## Exception stack traces

```[dbe07091][HTTP] --> POST /session/<session>/window/rect {"width":1260,"height":480}
[dbe07091][WindowsDriver@82b6] Encountered internal error running command: BadParametersError: The following required parameters are missing: ["x","y"]
Known required parameters are: ["x","y","width","height"]
You have provided: ["width","height"]
    at checkParams (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:155:9)
    at asyncHandler (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:362:7)
    at C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:512:15
    at Layer.handle [as handle_request] (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:284:15
    at param (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
    at param (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:421:3)
    at next (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
    at C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at invokeCallback (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\raw-body\index.js:238:16)
    at done (C:\Users\User\AppData\Roaming\npm\node_modules\appium\node_modules\raw-body\index.js:227:7)
[dbe07091][W3C] Bad parameters: BadParametersError: The following required parameters are missing: ["x","y"]
Known required parameters are: ["x","y","width","height"]
You have provided: ["width","height"]
[dbe07091][HTTP] <-- POST /session/<session>/window/rect 400 17 ms - 3378```

**Comment by mykola-mokhnach** [comment] 2024-08-02 13:47
Possible duplicate of https://github.com/appium/appium/issues/20390

**Comment by mykola-mokhnach** [comment] 2024-08-08 19:44
@sudo-plz Please verify if the workaround https://github.com/appium/appium-windows-driver/pull/271 works for you.

Use the guide at https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/branch-testing.md

**Closed as completed** 2024-08-09 07:20 UTC
