### ISSUE TITLE
Client fails to return correct element attribute value

### ISSUE THREAD

**Issue by saska123** [appium/appium-dotnet-driver#398] opened 2020-03-20 10:42 UTC
## Description

In my tests I want to enter some text into input box and then read it to make sure that input method succeeded. So in my code I use _element.SendKeys(value);_ and then I read it _var commentText = element.Text;_ I expect that read text would be the same as inputed text. But its not!
Before entering text into input box, box has prefilled value "Add comment". I enter the new text (this deletes the old text), read the element text and still get the old value "Add comment" but if I extract the PageSource "Add comment" text is not present anymore (my new entered text is present).

## Environment

* .NET client build version: 4.1.1
* Appium server version: 1.15.1
* Desktop OS/version used to run Appium if necessary: macOS Catalina 10.15.2
* Node.js version: 12.14.1
* Mobile platform/version under test: simulator iPhone 8+, iOS 12.4

## Code To Reproduce Issue

Before writing anything read the PageSource. Result:
`<XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Add comment" name="payment_attachments_comment_input" label="" enabled="true" visible="true" x="75" y="512" width="200" height="48"/>`
Using PageObject model write text into element like this: _element.SendKeys(value);_
Read the PageSource again. Result:
`<XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Test!!!😎" name="payment_attachments_comment_input" label="" enabled="true" visible="true" x="75" y="512" width="200" height="48"/>`
Now read it like this:
_var commentText = element.Text;_
Or like this:
_var commentText = element.GetAttribute("value");_
The read result is "Add comment".

**Comment by mykola-mokhnach** [comment] 2020-03-20 11:02
Duplicate of https://github.com/appium/appium/issues/13691

**Comment by saska123** [comment] 2020-03-20 12:50
My workaround for this issue:
```
var pageSource = Driver.Instance.PageSource;
Regex regex = new Regex("value=\"(.*?)\"");
var matches = regex.Matches(pageSource);
foreach (Match m in matches)
{
    var elementText = m.Groups[1].ToString();
    if (elementText.Contains(value))
    {
        commentText = elementText;
        break;
    }
}
```
Where _value_ is the text I enter into the input box and _commentText_ the real value that is read from Page Source.

**Closed** 2021-10-20 07:09 UTC
Labels: ThirdParty
